### PR TITLE
Created a review tile template with hardcoded placeholders and added the temporary review tile to the bottom of App component

### PR DESCRIPTION
**Pull request by bkern98**
I figured out how to use the Material UI grid and was able to style it similarly to how I think it will look in the final version.  Next step will be to create a Review List component that renders two of these and then to fill in the proper review info from the API.

### CODE REVIEW

**Comment by itsme-kristin** [comment]
Hey Ben! I'm showing that there is a conflict with the client/dis/bundle.js here in Github. I tried to checkout your branch to take a look, but it looked like the branch was created before the changes Don and I made. Maybe you could pull down the master to see where the conflict might be happening? Also, I'm not sure that Javascript is liking your '&' in 'Ratings & Reviews'

**Review by itsme-kristin — COMMENTED** [review]
Sorry, I think I left my comment in the wrong place! I put it into Conversation...

**Review by itsme-kristin — COMMENTED** [review]
Hey! I saw you deleted your bundle.js! Did you also pull my changes down before creating your pull request? Just so we don't run into merge conflicts down the line.

**Comment by bkern98** [comment]
> Hey! I saw you deleted your bundle.js! Did you also pull my changes down before creating your pull request? Just so we don't run into merge conflicts down the line.

Good catch! Just fixed that issue and it looks like all the conflicts are resovled.

**Review by itsme-kristin — APPROVED** [review]
Hey Ben! I checked it out, and it looks great! I did have to do `npm install` to get the ratings lab(?), but then everything was bundling properly. I will note that my server stopped working when I looked at your branch, but that could possibly be an error on my end, so I say you are good to merge!

**Pull request merged**
