### PR TITLE
Made necessary axios requests and populated state for product card

### PR DESCRIPTION
**Pull request by itsme-kristin**
This is really probably too big for a pull request, but I was on a roll and couldn't find a good stopping place! I made axios requests that populated state for my related products list and my product card. Then, I made a Material UI card component with the necessary information. If you look at our actual page, you will notice it is not in a horizontal configuration yet because I am still deciding whether I want a carousel or a horizontal scrolling image gallery.

### CODE REVIEW

**Review by UnlikelyHero — COMMENTED** [review]
Looks Pretty good...

During the TA i got pinged because I ran two Async Requests in my componentDidMount method I think they called it a "Async Race condition" and I was told that was something I needed to fix because this would essentially trigger 2 renders.

Unfortunately I'm not familiar how this works with hooks, so I think @bkern98 should take a look as a backup to make sure we're updating state once during the useEffect.

**Review by bkern98 — APPROVED** [review]
Looks really good. I'm guessing the return statements mean "if these conditions are true, render what is in parentheses"?)

**Comment by itsme-kristin** [comment]
> Looks Pretty good...
> 
> During the TA i got pinged because I ran two Async Requests in my componentDidMount method I think they called it a "Async Race condition" and I was told that was something I needed to fix because this would essentially trigger 2 renders.
> 
> Unfortunately I'm not familiar how this works with hooks, so I think @bkern98 should take a look as a backup to make sure we're updating state once during the useEffect.

Yeah, I was unsure of how to do it as well. When I split it into two different useEffects, it didn't render anything. I thought maybe I could get away with putting both async functions inside since they don't affect each other and my render was conditional upon both parts of state being defined? I had a couple of other ideas in my back pocket if it didn't work, but when it did, I decided to go with it! I'm happy to change it if it ends up being a problem later on.

**Comment by itsme-kristin** [comment]
> Looks really good. I'm guessing the return statements mean "if these conditions are true, render what is in parentheses"?)

Yes, I think it's called "lazy eval." I'm pretty sure it's just a different way of writing what you did in your render for App.js. I'll go ahead and merge!

**Pull request merged**
